-- SQL PROJECT

/* ===============================================================
    Grocery Store Management
    ==============================================================*/
    
CREATE DATABASE Grocery_Store;
USE Grocery_Store;

-- 1. Supplier Table
CREATE TABLE IF NOT EXISTS supplier (
    sup_id TINYINT PRIMARY KEY,
    sup_name VARCHAR(255),
    address TEXT
);

-- 2. Categories Table
CREATE TABLE IF NOT EXISTS categories (
    cat_id TINYINT PRIMARY KEY,
    cat_name VARCHAR(255)
);

-- 3. Employees Table
CREATE TABLE IF NOT EXISTS employees (
    emp_id TINYINT PRIMARY KEY,
    emp_name VARCHAR(255),
    hire_date VARCHAR(255)
);

-- 4. Customers Table
CREATE TABLE IF NOT EXISTS customers (
    cust_id SMALLINT PRIMARY KEY,
    cust_name VARCHAR(255),
    address TEXT
);

-- 5. Products Table
CREATE TABLE IF NOT EXISTS products (
    prod_id TINYINT PRIMARY KEY,
    prod_name VARCHAR(255),
    sup_id TINYINT,
    cat_id TINYINT,
    price DECIMAL(10,2),
    FOREIGN KEY (sup_id) REFERENCES supplier(sup_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (cat_id) REFERENCES categories(cat_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- 6. Orders Table
CREATE TABLE IF NOT EXISTS orders (
    ord_id SMALLINT PRIMARY KEY,
    cust_id SMALLINT,
    emp_id TINYINT,
    order_date VARCHAR(255),
    FOREIGN KEY (cust_id) REFERENCES customers(cust_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (emp_id) REFERENCES employees(emp_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- 7. Order_Details Table
CREATE TABLE IF NOT EXISTS order_details (
    ord_detID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    ord_id SMALLINT,
    prod_id TINYINT,
  
  quantity TINYINT,
    each_price DECIMAL(10,2),
    total_price DECIMAL(10,2),
    FOREIGN KEY (ord_id) REFERENCES orders(ord_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (prod_id) REFERENCES products(prod_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

select * from supplier;

-- Analysis Qustions
--- 1. Customer Insights
-- How many unique customers have placed orders?
SELECT 
    *
FROM
    customers;
 
-- Which customers have placed the highest number of orders?

SELECT 
    c.cust_name, COUNT(o.cust_id) AS o_c
FROM
    customers c
        JOIN
    orders o ON c.cust_id = o.cust_id
GROUP BY c.cust_name
ORDER BY o_c DESC;

-- What is the total and average purchase value per customer?
select * from order_details;
SELECT 
    c.cust_name,
    SUM(od.total_price) AS Total_purchase_value,
    round(AVG(od.total_price),2) AS avg_price
FROM
    customers c
        JOIN
    orders o ON c.cust_id = o.cust_id
        JOIN
    order_details od ON o.ord_id = od.ord_id
GROUP BY c.cust_name;
 
-- Who are the top 5 customers by total purchase amount?
SELECT c.cust_id,c.cust_name,
       SUM(od.total_price) AS Total_purchase_value
FROM customers c
JOIN orders o ON c.cust_id = o.cust_id
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY c.cust_name
ORDER BY Total_purchase_value DESC
LIMIT 5;
-- 2. Product Performance
-- How many products exist in each category?
SELECT 
    c.cat_name, COUNT(p.cat_id) as num_products
FROM
    categories c
        JOIN
    products p ON c.cat_id = p.cat_id
GROUP BY c.cat_name;

-- What is the average price of products by category?
SELECT 
    c.cat_name, round(AVG(price),2) AS avg_price_products
FROM
    categories c
        JOIN
    products p ON c.cat_id = p.cat_id
GROUP BY c.cat_name;

-- Which products have the highest total sales volume (by quantity)?
SELECT 
    p.prod_name, SUM(od.quantity) AS Volume
FROM
    products p
        JOIN
    order_details od ON p.prod_id = od.prod_id
GROUP BY p.prod_name;

-- What is the total revenue generated by each product?
select * from order_details;
SELECT 
    p.prod_name, SUM(od.total_price) revenue_by_products
FROM
    products p
        JOIN
    order_details od ON p.prod_id = od.prod_id
GROUP BY prod_name;

-- How do product sales vary by category and supplier?
SELECT
    c.cat_id,
    c.cat_name,
    SUM(od.quantity) AS total_quantity_sold,
    SUM(od.total_price) AS total_sales
FROM categories c
JOIN products p
    ON c.cat_id = p.cat_id
JOIN order_details od
    ON p.prod_id = od.prod_id
GROUP BY c.cat_id, c.cat_name
ORDER BY total_sales DESC;

-- 3. Sales and Order Trends
-- How many orders have been placed in total?
SELECT 
    COUNT(ord_id) AS total_orders
FROM
    orders;

-- What is the average value per order?

SELECT 
    o.ord_id, round(AVG(od.total_price),2) AS avg_price
FROM
    orders o
        JOIN
    order_details AS od ON o.ord_id = od.ord_id
GROUP BY od.ord_id;

-- On which dates were the most orders placed?
SELECT 
    order_date, COUNT(ord_id) AS num_orders
FROM
    orders
GROUP BY order_date
order by num_orders desc;

-- What are the monthly trends in order volume and revenue?

SELECT 
    SUBSTR(o.order_date, 1, 1) AS month,
    COUNT(o.ord_id) AS count_of_orders,
    SUM(od.total_price) AS Revenue
FROM
    orders o
        JOIN
    order_details od ON o.ord_id = od.ord_id
GROUP BY month
ORDER BY Revenue DESC
;

-- How do order patterns vary across weekdays and weekends?
SELECT
    CASE
        WHEN DAYOFWEEK(order_date) IN (1,7)
        THEN 'Weekend'
        ELSE 'Weekday'
    END AS day_type,
    COUNT(*) AS total_orders
FROM orders
GROUP BY day_type;

-- 4️. Supplier Contribution
-- How many suppliers are there in the database?
SELECT 
    COUNT(sup_id)
FROM
    supplier;

-- Which supplier provides the most products?
SELECT 
    s.sup_name, COUNT(p.sup_id) AS most_provider
FROM
    supplier s
        JOIN
    products p ON s.sup_id = p.sup_id
GROUP BY s.sup_id
ORDER BY most_provider DESC
LIMIT 1;

-- What is the average price of products from each supplier?
SELECT 
    s.sup_name, round(AVG(p.price),2) avg_prize
FROM
    supplier s
        JOIN
    products p ON s.sup_id = p.sup_id
GROUP BY s.sup_name;

-- Which suppliers contribute the most to total product sales (by revenue)?
SELECT 
    s.sup_name, SUM(od.total_price) total_revenue
FROM
    supplier s
        JOIN
    products p ON s.sup_id = p.sup_id
        JOIN
    order_details od ON od.prod_id = p.prod_id
GROUP BY s.sup_name;

-- 5️. Employee Performance

-- How many employees have processed orders?
SELECT 
    COUNT(emp_id)
FROM
    employees;

-- Which employees have handled the most orders?
SELECT 
    e.emp_name, COUNT(o.ord_id)
FROM
    employees e
        JOIN
    orders o ON e.emp_id = o.emp_id
GROUP BY e.emp_name;

-- What is the total sales value processed by each employee?
SELECT 
    e.emp_name, SUM(od.total_price)
FROM
    employees e
        JOIN
    orders o ON e.emp_id = o.emp_id
        JOIN
    order_details od ON od.ord_id = o.ord_id
GROUP BY e.emp_name;


-- What is the average order value handled per employee?
SELECT 
    e.emp_name, ROUND(AVG(od.total_price), 2)
FROM
    employees e
        JOIN
    orders o ON e.emp_id = o.emp_id
        JOIN
    order_details od ON o.ord_id = od.ord_id
GROUP BY e.emp_name;


-- 6️. Order Details Deep Dive
-- What is the relationship between quantity ordered and total price?
SELECT 
    od.ord_detID,
    p.prod_name,
    od.quantity,
    od.each_price,
    od.total_price
FROM order_details od
JOIN products p
    ON od.prod_id = p.prod_id;

-- What is the average quantity ordered per product?
SELECT 
    p.prod_name, AVG(od.quantity) AS avg_quantity
FROM
    order_details od
        JOIN
    products p ON od.prod_id = p.prod_id
GROUP BY prod_name;

-- How does the unit price vary across products and orders?
SELECT
    ord_detID,
    quantity,
    each_price,
    total_price,
    (quantity * each_price) AS calculated_total
FROM order_details;


